cleverClub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
#from .import views /admin/customuser/add/

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('custom_admin.urls')),
    path('', include('user.urls', namespace="user")),
    path('', include('home.urls')),
    path('', include('musicStudio.urls')),
    path('', include('sections.urls')),
    path('trigger-404/', views.trigger_404),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name="home"

urlpatterns = [
    path('', views.home, name='home'),
]

user/urls.py
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path('register', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

cleverClub/views.py
from django.http import Http404
from django.shortcuts import render

def trigger_404(request):
    raise Http404("This is a test 404 error")

cleverClub/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %}My Site{% endblock %}</title>

    <link rel="icon" href="{% static 'imgs/Infinite Dream-logos_transparent0.png' %}" type="image/x-icon" />

    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Danfo&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Foldit:wght@100..900&display=swap" rel="stylesheet">
    
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&family=Short+Stack&display=swap" rel="stylesheet">

    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/menu.css' %}">

    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js" integrity="sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    {% block extrahead %}
    {% endblock %}
    <style>
        button {
            border: 1px solid rgb(221,90,68);
        }
        button:hover {
            background-color: rgba(250, 201, 211, 0.438);
        }
        footer {
            height: 38px;
            text-align: right;
            background-color: #F3DCD0;
            /* margin-top: 40px; */
            padding: 7px;
            color: black;
            box-shadow: 0px 0px 4px #F3DCD0;
            /* width: 100%; */
        }
        footer a {
            text-decoration: none;
            color: rgb(221,90,68);
        }
    </style>
    {% block extrastyle %}
    {% endblock %}
    
</head>
<body id="the-body">

    <main class="main" id="main">
        {% block main %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock %}

    {% include "footer.html" %}
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> -->

    <script>
        $("#icon-user-menu").on("click", function() {
            $("#user-menu").toggle("show")
        })
    </script>
</body>
</html>

cleverClub/templates/footer.html
<footer>
    <p>Made with ❤️ by <a href="https://www.linkedin.com/in/1128khouloud/">Khouloud</a> &copy;2024</p>
</footer>

cleverClub/templates/home_page_header.html
<header>
    {% include 'top-navbar.html' %}
    {% if user.is_authenticated %}
        {% include 'user-dash.html' %}
    {% else %}
    <div id="about-section">
        <div>
            <h1>Welcome to the AI Galaxy!</h1>
            <p class="typewrite" data-period="8000" 
            data-type='[ "Our platform is where education and entertainment come together!", 
            "Our mission is to make learning fun and effective by enhancing creativity, imagination, and analyzing skills.", 
            "Assisted by advanced AI, we provide personalized and innovative resources and interactive tools for students, teachers, and curious minds alike.", 
            "Join us on this exciting journey to make education enjoyable and accessible for all!" 
            ]'>
                <span class="wrap"></span>
            </p>
        </div>    
    </div>
    {% endif %}
</header>

cleverClub/templates/home_page_menu.html
<div id="top-left-menu">
    
        {% if user.is_authenticated %}
        <div id="btn-user-menu"><button id="icon-user-menu"><i class="fa fa-user"></i></button></div>
        <div id="user-menu">
            <ul >
                <li>
                    <a href="#">Hello {{ user.username }}!</a>
                </li>
                <li><a href="#"><i class="fa fa-user"></i> My Profile</a></li>
                <li><a href="#"><i class="fa fa-book"></i> My Courses</a></li>
                <li><a href="#"><i class="fa fa-chart-line"></i> My Progress</a></li>
                <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                <li>
                <form method="post" action="{% url 'user:logout' %}">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form></li>
            </ul>
        </div>
        {% else %}
        <ul>
            <li><a href="{% url 'user:login' %}">Login</a></li>
            <li><a href="{% url 'user:register' %}">Register</a></li>
        </ul>
        {% endif %}
    
</div>

cleverClub/templates/top-navbar.html
{% load static %}
<nav id="header-nav">
    <div id="logo">
        <a href="{% url 'home:home' %}"><img src="{% static 'imgs/Infinite Dream-logos_transparent0.png' %}" alt="logo"></a>
        <!-- <p><a href="">Clever Club</a></p> -->
    </div>

    {% include 'home_page_menu.html' %}
</nav>