cleverClub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
#from .import views /admin/customuser/add/

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('custom_admin.urls')),
    path('', include('user.urls', namespace="user")),
    path('', include('home.urls')),
    path('', include('musicStudio.urls')),
    path('', include('sections.urls')),
    path('trigger-404/', views.trigger_404),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name="home"

urlpatterns = [
    path('', views.home, name='home'),
]

musicStudio/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name="musicStudio"

urlpatterns = [
    path('studio', login_required(views.studio), name='studio'),
    path('native', views.native, name='native'),
    path('generateMusic',login_required(views.generateMusic), name='generate.music'),
    path('studio/getSelectedTones/<int:generated_id>/', login_required(views.getSelectedTones), name='getSelectedTones'),
    path('create_music', login_required(views.create_music), name='create_music'),
    path('task_status/<str:job_id>/', login_required(views.get_task_status), name='task_status'),
] 

sections/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name="sections"

urlpatterns = [
    path('section/<int:section_id>/', views.SectionPage, name='section'),
    path('section/<int:section_id>/<str:category_name>/<int:category_id>/content/<int:content_id>/', views.ContentPage, name='content'),
    path('categories', views.CategoryPage, name='categories'),
   
]

sections/models.py
from typing import Any
from django.db import models
from django.conf import settings
# from cleverClub.utils import GenerateAnything
from django.utils.translation import gettext_lazy as _

from django_ckeditor_5.fields import CKEditor5Field


class Section(models.Model) :
    title = models.CharField(max_length=30)
    picture = models.ImageField(upload_to='imgs/uploads/sections/%Y/')
    tagId = models.CharField(max_length=30)
    description = models.TextField()
    # admin who created it
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='admin_section', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["id"]
    
    def categories(self):
        """ return related """
        return self.category_set.all()
        # print("categories", request.user.is_staff)
        # if request.user.is_staff:
        #     return self.category_set.all()
        # return self.category_set.all().filter(is_published=True)

    def __str__(self):
        return f"{self.title}, {self.updated_at}"


class Category(models.Model) :

    title =  models.CharField(max_length=100)
    # tagId = models.CharField(max_length=30)
    # picture =  models.ImageField(upload_to='imgs/uploads/categories/%Y/')
    description =  models.TextField()
    section = models.ForeignKey("Section", on_delete=models.CASCADE)
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='admin_category', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["id"]

    def contents(self):
        return self.content_set.all()
        # if request.user.is_staff:
        #     return self.content_set.all()
        # return self.content_set.all().filter(is_published=True)

    
    def __str__(self):
        return f"{self.section.title}: {self.title}"# ,{self.updated_at}"

class Content(models.Model) :
    TYPES = (
        ('Course', _('Course')),
        ('Puzzle', _('Puzzle')),
        ('Quiz', _('Quiz')),
        ('Story', _('Story')),
        ('Manga', _('Manga')),
    )
    LEVELS = (
        ('Beginner', _('Beginner')),
        ('Medium', _('Medium')),
        ('Advanced', _('Advanced')),
    )

    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='admin_content', on_delete=models.CASCADE)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    level = models.CharField(max_length=30, choices=LEVELS)
    contentType = models.CharField(max_length=30, verbose_name="Content Type", choices=TYPES, default="Course")
    title =  models.CharField(max_length=30)
    description =  CKEditor5Field(config_name='default')
    # section = models.ForeignKey("Section", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    text = CKEditor5Field(blank=True,null=True, verbose_name="Content (editing works only through the json field for now!)", config_name='admin')
    json = models.TextField(blank=True,null=True)
    is_published = models.BooleanField(default=False, verbose_name="Publish Content?")
    
    class Meta:
        ordering = ["id"]

    def exercices(self):
        return self.exercices_set.all()
        # if request.user.is_staff:
        #     return self.exercices_set.all().filter(is_published=True)
        # return self.exercices_set.all()
    
    def __str__(self):
        return f"{self.title}, {self.updated_at}"


class Enrolments(models.Model) :
    content = models.ForeignKey("Content", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_enrolment', on_delete=models.CASCADE)
    
    enrolled_at = models.DateTimeField(auto_now_add=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.first_name}, {self.user.last_name} {self.updated_at}"
    

class Exercices(models.Model):
    # if it's related to content it follows else we chose the level
    LEVELS = (
        ('Beginner', _('Beginner')),
        ('Medium', _('Medium')),
        ('Advanced', _('Advanced')),
    ) 
    name = models.CharField(max_length=30, default="Exercice") # exce number + name
    content = models.ForeignKey("Content", on_delete=models.CASCADE, null=True) # the exercice can belong to a content or can be general

    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='admin_exercice', on_delete=models.CASCADE)
    level = models.CharField(max_length=30, choices=LEVELS, null=True)
    question = models.TextField(null=True)
    answer = models.TextField(null=True)
    pictures = models.ForeignKey("Pictures", on_delete=models.CASCADE, null=True)
    is_published = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    def choices(self):
        return self.exercicechoices_set.all()
        # if request.user.is_staff:
        #     return self.exercicechoices_set.all()
        # return self.exercicechoices_set.all().filter(is_published=True)

    def __str__(self):
        return f"{self.name}"


class ExerciceChoices(models.Model):
    exercice = models.ForeignKey("Exercices", on_delete=models.CASCADE, null=True) 
    name = models.CharField(max_length=30, null=True)
    choice = models.TextField(null=True)
    answer = models.TextField(null=True) # True / False or Text

    picture = models.ForeignKey("Exercices", related_name='exercice_picture', on_delete=models.CASCADE, null=True) # a choice
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.choice}"


class Pictures(models.Model):
    TYPES = (
        ('Exercice', 'Exercice'),
        ('Content', 'Content'),
    )
    title = models.CharField(max_length=30)
    pictureType = models.CharField(max_length=100, choices=TYPES)
    picture = models.ImageField(upload_to='imgs/uploads/contents/%Y/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    

class UserProgress(models.Model) :
    content = models.ForeignKey("Content", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_progress', on_delete=models.CASCADE)
    done = models.BooleanField(default=False)
    page = models.CharField(max_length=30) # link to the page
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class UserExcerciceGrade(models.Model) :
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_grade', on_delete=models.CASCADE)
    exercice = models.ForeignKey("Exercices", on_delete=models.CASCADE)
    done = models.BooleanField(default=False)
    trial = models.IntegerField()
    grade = models.DecimalField(max_digits=3, decimal_places=3)

sections/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .models import *
from django.db.models import Prefetch

def SectionPage(request, section_id):
    """ show section page """
    if request.user.is_staff:
        getSection= get_object_or_404(Section, id=section_id)
        #getCategories = getSection.categories()
        getAllSections = Section.objects.select_related().all().values("id", "title")
    else:
        getSection= get_object_or_404(Section, id=section_id, is_published=True)
        #getCategories = getSection.categories(is_published=True)
        getAllSections = Section.objects.select_related().all().filter(is_published=True).values("id", "title")
    
    return render(request, 'section.html',{"getSection": getSection, "getAllSections": getAllSections})

def ContentPage(request, section_id, category_name, category_id, content_id):
    """ show content page """
    if request.user.is_staff:
        getContent= get_object_or_404(Content, id=content_id, category_id=category_id)
        getAllContents = Content.objects.all().filter(category_id=category_id).values("id", "title", "contentType")
    else:
        getContent= get_object_or_404(Content, id=content_id, category_id=category_id, is_published=True)
        getAllContents = Content.objects.all().filter(category_id=category_id, is_published=True).values("id", "title", "contentType")
    return render(request, 'content.html',{"getContent": getContent, 
                                           "getAllContents": getAllContents,
                                           "section_id": section_id,
                                           "category_name": category_name,
                                           "category_id": category_id
                                           })

def CategoryPage(request):
    """ show categories per section """
    if request.user.is_staff:
        # user.is_authenticated
        getSections = Section.objects.select_related().all()
    
        getCategories = Category.objects.select_related().all()
        # data_dict = model_to_dict(getSectios)
    else:
        published_categories = Category.objects.filter(is_published=True)
        getSections = Section.objects.prefetch_related(
            Prefetch('Category', queryset=published_categories)
        )

        published_contents = Content.objects.filter(is_published=True)
        getCategories = Category.objects.prefetch_related(
            Prefetch('Content', queryset=published_contents)
        )

    print(getSections)

    # return render(request, 'home.html',{'getSections': getSections})
    return render(request, 'categories.html',{'getCategories': getCategories, "getSections": getSections})

sections/templates/categories.html
{% extends "base.html" %}
{% load static %}

{% block content %}
        
    {% include 'top-navbar.html' %}


{% for section in getSections %}

{{ section.title }}
<br>

{% for category in section.categories %}
*** {{ category.title }}
<br>

{% endfor %}
{% endfor %}

{% endblock %}

sections/templates/content.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ getContent.title }}
{% endblock %}

{% block extrastyle %}
<style>
    body {
        background-color: black;
    }
    .main {
        min-height: 100vh;
        padding-bottom: 40px;
        /* background-color: rgb(1, 32, 56); */
        font-family: "Short Stack", cursive;
        font-weight: 500;
        font-style: normal;
    }
    #section-container {
        display: flex;
        margin-top: 1%;
        min-width: 700px;

    }
    .section-contents {
        width: 80%;
        min-height: 87vh;
        margin: auto;
        /* font-family: Arial, sans-serif; */
        border-radius: 10px;
        /* background-color: cornflowerblue; */

        background-color: #F3DCD0;
        padding: 20px;
        box-sizing: border-box;
        /* flex: 1; */
        box-shadow: 0px 0px 5px 5px gray;
    }
    .section-contents .contents {
        width: 95%;
        margin: auto;
    }
    .section-contents .contents li {
        list-style: none;
        margin-left: 20px;
        padding: 5px;
    }
    .section-contents .contents input {
        border: 1px intset rgb(187, 185, 183);
        border-radius: 8px;
        padding: 3px;
    }
    .section-contents .contents img {
        display: block;
        margin: auto;
        /* width: 300px;
        height: 300px; */
    }
    .level {
        padding: 2px 5px;
        border-radius: 5px;
        font-size: 0.6rem;
    }
    .Beginner {
        background-color: lightgreen;
    }
    .Medium {
        background-color: lightyellow;
    }
    .Advanced {
        background-color: lightcoral;
    }

    .sections-menu {
        width: 20%;
        /* display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap; */
    }
    .sections-menu .sections-menu-elements {
        padding: 10px;
        display: block;
        /* background-color: rgba(31, 97, 251, 0.25); */
        /* background-color: aliceblue; */
        margin: 5px;
        box-shadow: 0px 0px 1px 2px gray;
        /* height: 100px; */

    }
    .sections-menu .sections-menu-elements:hover {
        background-color: #F3DCD0;
    }
    .sections-menu a {
        text-decoration: none;
        color: coral;

    }
    .active {
        background-color: #F3DCD0;
        color: rgb(194, 79, 59);
    }
    .contents {
        min-width: 560px;
    }
    /* .grid-cell {
        width: 9%;
        text-align: center;
    } */
    #sudoku-grid input {
        width: 35px;
        height: 35px;
        text-align: center;
    }
    .prefilled {
        background-color: aliceblue;
    }
    #puzzle-container {
        margin-left: 10%;
        text-align: center;
    }
    .links a {
        color: rgb(112, 151, 244);
        text-decoration: none;
        font-weight: bold;
    }
    h1 {
        color:rgb(6, 54, 167)
    }
    h2 {
        color:rgb(31, 97, 251)
    }
    h3 {
        color:rgb(83, 26, 241);
    }
    h4 {
        color:rgb(50, 77, 252)
    }
    h5 {
        color: rgb(98, 41, 255);
    }
    p {
        color: rgb(1, 25, 80);
        padding-bottom: 18px;
    }
    @media screen and (max-width: 1024px) {
        .sections-menu {
            width: 100%;
            display: flex;
            justify-content: space-around;
            overflow-x: scroll;
            order: 1;

        }
        #section-container {
            flex-direction: column;
        }
        .section-contents  {
            width: 100%;
            order: 2;
        }
    }
</style>


{% endblock %}

{% block main %}
        
{% include 'top-navbar.html' %}

<section id="section-container">

    <div class="section-contents">
        <div class="links"><a href="{% url 'sections:section' getContent.category.section.id %}">{{ getContent.category.section.title }}</a> > <a href="#">{{getContent.category.title}}</a> > <a href="{% url 'sections:content' getContent.category.section.id getContent.category.title getContent.category.id getContent.id %}">{{getContent.title}}</a> </div>
        <hr>
        <div class="contents">
                <div>{{ getContent.text|safe }}</div>
        </div>

    </div>
    <div class="sections-menu">
        {% for content in getAllContents %}
        <!--   content.category.section.id  -->
        <a href="{% url 'sections:content' section_id category_name category_id content.id %}">
            <span class="sections-menu-elements {% if getContent.id == content.id %} active {% endif %}">{{ content.title }} - {{ content.contentType }}</span>
        </a>
        
        {% endfor %}
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
// scale content images
let images = document.querySelectorAll('.contents img')
for (let i = 0; i < images.length; i++){
    let scaller = 1
    if (images[i].offsetWidth >= 900) {
        scaller = 3
    }
    if (images[i].offsetWidth > 1800) {
        scaller = 6
    }
    
    let width = (images[i].offsetWidth / scaller) + "px"
    let height  = (images[i].offsetHeight / scaller) + "px"
    images[i].setAttribute('style', `width:${width}; height:${height};`)

}

</script>
<!-- <script type="text/javascript" src="{% static '/js/matrix.js' %}"></script> -->
{% endblock %}

sections/templates/section.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ getSection.title }}
{% endblock %}

{% block extrastyle %}

<style>
    body {
        background-color: black;
    }
    .main {
        min-height: 100vh;
        padding-bottom: 40px;
        /* background-color: rgb(1, 32, 56); */
        font-family: "Short Stack", cursive;
        font-weight: 400;
        font-style: normal;
    }
    #section-container {
        display: flex;
        margin-top: 1%;

    }
    .section-contents {
        width: 83%;
        min-height: 87vh;
        margin: auto;
        /* font-family: Arial, sans-serif; */
        border-radius: 10px;
        /* background-color: cornflowerblue; */

        background-color: #F3DCD0;
        padding: 20px;
        box-sizing: border-box;
        /* flex: 1; */
        box-shadow: 0px 0px 5px 5px gray;
    }
    .section-contents .contents {
        /* margin-top: 20px; */
        display: flex;
        justify-content: space-around;
        align-items: flex-start;
    }
    .section-picture {
        margin-right: 3%;
    }
    /* .section-details {
        
    } */
    .level {
        padding: 2px 5px;
        border-radius: 5px;
        font-size: 0.6rem;
    }
    .Beginner {
        background-color: lightgreen;
    }
    .Medium {
        background-color: lightyellow;
    }
    .Advanced {
        background-color: lightcoral;
    }
    .category-contents li {
        list-style-type: none;
        margin-left: 25px;
        
        /* font-size: 0.9rem; */
    }
    .category-contents a {
        text-decoration: none;
        color: black;
    }
    .sections-menu {
        width: 17%;
        /* display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap; */
        max-height: 100vh;
        overflow-y: scroll;
    }
    
    .sections-menu .sections-menu-elements {
        padding: 10px;
        display: block;
        /* background-color: rgba(31, 97, 251, 0.25); */
        /* background-color: aliceblue; */
        margin: 5px;
        box-shadow: 0px 0px 1px 2px gray;
        /* height: 100px; */

    }
    .sections-menu .sections-menu-elements:hover {
        background-color: #F3DCD0;
    }
    .sections-menu a {
        text-decoration: none;
        color: coral;

    }
    .active {
        background-color: #F3DCD0;
        color: rgb(194, 79, 59);
    }
    .contentType {
        padding: 5px;
        background-color: rgb(246,151,142) ;
        color: rgb(130, 84, 255);
        /* border-left: 3px solid black; */
        border-right: 3px ridge black;
        border-top: 8px solid #F3DCD0;
        border-bottom: 8px solid #F3DCD0;

        /* border-top-right-radius: 20px; */
    }
    .extra-tools {
        text-align: center;
    }
    .extra-tools a {
        color: rgb(194, 79, 59);
        text-decoration: none;
    }
  
    h1 {
        color:rgb(6, 54, 167)
    }
    h2 {
        color:rgb(31, 97, 251)
    }
    h3 {
        color:rgb(83, 26, 241);
    }
    h4 {
        color:rgb(50, 77, 252)
    }
    h5 {
        color: rgb(98, 41, 255);
    }
    p {
        color: rgb(1, 25, 80);
    }
    @media screen and (max-width: 1024px) {
        .sections-menu {
            width: 100%;
            display: flex;
            justify-content: space-around;
            overflow-x: scroll;
            order: 1;

        }
        #section-container {
            flex-direction: column;
        }
        .section-contents  {
            width: 100%;
            order: 2;
        }
        .section-picture {
            display: none;
        }
    }
    
</style>

{% endblock %}

{% block main %}
        
{% include 'top-navbar.html' %}

<section id="section-container">

<div class="section-contents matrix-content ">
    
    <div class="contents">
        <div class="section-picture">
            <img src="/media/{{ getSection.picture }}" width="300px" height="370px" alt="{{ getSection.title }}"/>
            {% if getSection.title == "Music Section" %}
            <div class="extra-tools">
                <a href="{% url 'musicStudio:studio' %}">Make some melodies?!</a>
            </div>
            {% endif %}
        </div>
        <div class="section-details">
            <div>
                <h2>{{ getSection.title }}</h2>
                <p>{{ getSection.description }}</p>
            </div>
            <div>
                <div>
                    <h3>Section Contents</h3>
                </div>
                
                {% for category in getSection.categories %}
                {% if user.is_staff %}
                <ul class="category-contents"><h4>{{ category.title }}</h4>
                 
                    {% for content in category.contents %}
                    <li>
                        <a href="{% url 'sections:content' getSection.id category.title category.id content.id %}"><h5><span class="contentType">{{ content.contentType }}</span>  {{ content.title }} <span class="level {{ content.level }}">{{ content.level }}</span></h5> 
                        <div class="content-details">
                            <p>{{ content.description|safe }}  </p>
                        </div></a> 
                        <hr>

                    </li>
                    {% endfor %}
                </ul>
                {% elif category.is_published %}
                <ul class="category-contents"><h4>{{ category.title }}</h4>
                 
                    {% for content in category.contents %}
                    {% if content.is_published %}
                    <li>
                        <a href="{% url 'sections:content' getSection.id category.title category.id content.id %}"><h5><span class="contentType">{{ content.contentType }}</span>  {{ content.title }} <span class="level {{ content.level }}">{{ content.level }}</span></h5> 
                        <div class="content-details">
                            <p>{{ content.description|safe }}  </p>
                        </div></a> 
                        <hr>

                    </li>
                    {% endif %}

                    {% endfor %}
                </ul>
                {% endif %}

                {% endfor %}
            </div>
        </div>
    </div>

</div>
<div class="sections-menu">
    {% for section in getAllSections %}
    <a href="{% url 'sections:section' section.id %}">
        <span class="sections-menu-elements {% if getSection.id == section.id %} active {% endif %}">{{ section.title }}</span>
    </a>
    
    {% endfor %}
</div>
</section>
{% endblock %}

{% block scripts %}
<!-- <script type="text/javascript" src="{% static '/js/matrix.js' %}"></script> -->
{% endblock %}